# Generated by Django 4.2.10 on 2024-07-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='placeholder.jpg', upload_to='images/'),
        ),
    ]
