# Generated by Django 4.2.10 on 2024-03-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_destination_post_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.CharField(choices=[('europe', 'Europe'), ('northamerica', 'North America'), ('southamerica', 'South America'), ('centralamerica', 'Central America'), ('asia', 'Asia'), ('africa', 'Africa'), ('antarctica', 'Antarctica'), ('australia', 'Australia'), ('newzealand', 'New Zealand & The Pacific'), ('caribbean', 'The Caribbean'), ('middleeast', 'The Middle East')], default='europe'),
        ),
    ]
