# Generated by Django 4.2.10 on 2024-03-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
