# Generated by Django 4.2.10 on 2024-06-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
